Key pair
hetznercloud/packer-plugin-hcloud pull request #30
Opened 2022-01-29 21:16 UTC by ThorstenHeck

**DELETE THIS TEMPLATE BEFORE SUBMITTING**

In order to have a good experience with our community, we recommend that you
read the contributing guidelines for making a PR, and understand the lifecycle
of a Packer Plugin PR:

https://github.com/hashicorp/packer-plugin-hcloud/blob/main/.github/CONTRIBUTING.md#opening-an-pull-request

Describe the change you are making here!

Please include tests. We recommend looking at existing tests as an example. 

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #xxx
Closes #xxx

2022-01-29 21:16 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-hcloud?pullRequest=30)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-hcloud?pullRequest=30)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-hcloud?pullRequest=30).</sub>

2022-02-05 23:05 UTC, ThorstenHeck commented
Add bunch of new features regarding snapshot lifecycle management and private networking - wrote docs for ssh connection networking and lifeccle management.

2022-08-03 22:32 UTC, nywilken requested changes
Hi there @ThorstenHeck thanks for the contribution and apologies for the delayed review here. I just merged in another PR to enhance the SSH key generation logic. Can you please rebase and remove any duplicative changes. 

That said, when it comes to opening PRs it is best to open one PR per enhance or bug so that we can better review and understand the changes. We prefer multiple PRs over one big PR. Once you've rebased and the changes for the network to server feature changes have been consolidate ping @hashicorp/packer and we will give this a review. Cheers!

2023-09-25 14:08 UTC, nywilken commented
Hi there :wave:, I'm going to close this pull request since there hasn't been any updates to it. But if you are still running into issues please feel free to leave a comment on the change  and we will gladly reopen.

2023-09-25 14:08 UTC, closed without merging